# Site settings
title: codestars.eu
email: ole.michaelis@gmail.com
description: >
  Personal homepage of Ole Michaelis – Working @DNSimple,
  curator of @socodedconf and @slidrio. Passionate Software Engineer.
  I ♥️ elixir, ruby, node, metrics, NoSQL and all bleeding edge stuff!
url: "http://codestars.eu" # the base hostname & protocol for your site

author:
  twitter: CodeStars
twitter:
  username: CodeStars
github:
  username:  nesQuick

permalink: /:year/:title

# Build settings
exclude:
  - example

highlighter: rouge

gems:
  - jekyll-seo-tag
